get dc from existing image

diff --git a/container/Dockerfile b/container/Dockerfile
--- a/container/Dockerfile
+++ b/container/Dockerfile
@@ -1,11 +1,3 @@
-FROM python:3-alpine AS dc-builder
-
-RUN apk add linux-headers gcc libffi-dev musl-dev openssl-dev make
-
-RUN pip install docker-compose
-
-# ----
-
 FROM python:3-alpine
 
 ARG GIT_BRANCH
@@ -22,7 +14,7 @@ LABEL git.build.time=${GIT_BUILD_TIME}
 LABEL travis.build.number=${TRAVIS_BUILD_NUMBER}
 LABEL travis.build.web.url=${TRAVIS_BUILD_WEB_URL}
 
-COPY --from=dc-builder /usr/local/bin/docker-compose /usr/local/bin/
+COPY --from=nuvladev/job-docker-compose-client:master /usr/local/bin/docker-compose /usr/local/bin/
 
 ADD target/job /target/job
 
@@ -73,8 +65,19 @@ ADD https://raw.githubusercontent.com/docker-library/docker/65fab2cd767c10f22ee6
 RUN curl -s -L https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && \
             install /tmp/docker-machine /usr/local/bin/docker-machine
 
-# TODO: this only works for amd64
-RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl && kubectl version --client=true
+RUN set -eux; \
+    	\
+    	apkArch="$(apk --print-arch)"; \
+    	case "$apkArch" in \
+    		x86_64) kubectlArch='amd64' ;; \
+    		armv7) kubectlArch='arm' ;; \
+    		*) echo >&2 "error: unsupported architecture ($apkArch) for kubectl"; exit 1 ;;\
+    	esac; \
+    	\
+    	curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/${kubectlArch}/kubectl && \
+    	chmod +x ./kubectl && \
+    	mv ./kubectl /usr/local/bin/kubectl && \
+    	kubectl version --client=true
 
 RUN apk --no-cache add gettext
 
